### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by wellkunnected** [roccoma504/Rounds#4]
Hi,

I tried logging in to the app using the provided information for the facebook login and after telling I've already authorized Rounds it tells me the login failed. Any ideas?

**Comment by roccoma504** [comment]
Hey there. The test user names were used by me and the udacity  team for testing. Once permissions are granted the app doesn't ask for them again it just informs you that the app is already registered. You can use any Facebook login you want, not just these test ones and it'll work just fine. Let me know if you have any issues with your personal Facebook.

**Comment by wellkunnected** [comment]
Hi Matt,

Thanks for your help, I'll give that a try today! Cheers :)
